services:
  host:
    build:
      context: .
      dockerfile: packages/host/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - remote-angular

  remote-angular:
    build:
      context: .
      dockerfile: packages/remote-angular/Dockerfile
    ports:
      - "4201:80"
